const { readFileSync, writeFileSync } = require("node:fs");
const { join } = require("node:path");

const ROOT = join(__dirname, "..");
const INDEX_PATH = join(ROOT, "src", "data", "glossary.index.json");

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function nextAction(record) {
  if (record.status === "reviewed") return "ready; keep regression coverage current";
  if (record.status === "native-reviewed") return "close official/X QA before reviewed";
  if (record.status === "community-reviewed") return "complete X check and native review";
  if (record.status === "llm-audited") return "request community/native review";
  return "audit high-risk terms, then request community/native review";
}

function rowsFromIndex(index = readJson(INDEX_PATH)) {
  return index.glossaries.map((record) => ({
    locale: record.locale,
    language: record.language,
    status: record.status,
    terms: record.termCount,
    official: record.officialAlignment || "unknown",
    x: record.xTranslationCheck || "unknown",
    next: nextAction(record)
  }));
}

function summaryFromRows(rows) {
  const draftCount = rows.filter((row) => row.status === "llm-drafted").length;
  const auditedCount = rows.filter((row) => row.status === "llm-audited").length;
  const reviewedCount = rows.filter((row) => row.status === "reviewed").length;
  const communityReviewedCount = rows.filter((row) => row.status === "community-reviewed").length;
  const nativeReviewedCount = rows.filter((row) => row.status === "native-reviewed").length;
  return {
    auditedCount,
    draftCount,
    reviewedCount,
    communityReviewedCount,
    nativeReviewedCount,
    inReviewCount:
      rows.length - reviewedCount - auditedCount - draftCount - communityReviewedCount - nativeReviewedCount,
    totalPacks: rows.length,
    totalTerms: rows.reduce((sum, row) => sum + Number(row.terms || 0), 0)
  };
}

function formatConsole(rows) {
  const columns = [
    ["locale", 8],
    ["language", 22],
    ["status", 20],
    ["terms", 7],
    ["official", 10],
    ["x", 10],
    ["next", 0]
  ];

  const lines = [];
  lines.push(columns.map(([key, width]) => (width ? key.padEnd(width) : key)).join("  "));
  lines.push(columns.map(([, width]) => "-".repeat(width || 42)).join("  "));
  for (const row of rows) {
    lines.push(
      columns
        .map(([key, width]) => {
          const value = String(row[key]);
          return width ? value.padEnd(width) : value;
        })
        .join("  ")
    );
  }

  const summary = summaryFromRows(rows);
  lines.push("");
  lines.push(
    `summary: ${summary.totalPacks} packs, ${summary.reviewedCount} reviewed, ${summary.nativeReviewedCount} native-reviewed, ${summary.communityReviewedCount} community-reviewed, ${summary.auditedCount} llm-audited, ${summary.draftCount} llm-drafted, ${summary.inReviewCount} in review`
  );
  return `${lines.join("\n")}\n`;
}

function formatMarkdown(index = readJson(INDEX_PATH)) {
  const rows = rowsFromIndex(index);
  const summary = summaryFromRows(rows);
  const lines = [
    "# Glossary Status",
    "",
    "Generated from `src/data/glossary.index.json`. Do not edit this file by hand.",
    "",
    `Summary: ${summary.totalPacks} premium packs, ${summary.totalTerms} terms, ${summary.reviewedCount} reviewed, ${summary.nativeReviewedCount} native-reviewed, ${summary.communityReviewedCount} community-reviewed, ${summary.auditedCount} AI-audited beta packs, ${summary.draftCount} AI-drafted beta packs, ${summary.inReviewCount} in review.`,
    ""
  ];

  for (const row of rows) {
    lines.push(`## ${row.locale} - ${row.language}`);
    lines.push("");
    lines.push(`Status: \`${row.status}\``);
    lines.push(`Terms: ${row.terms}`);
    lines.push(`Official alignment: ${row.official}`);
    lines.push(`X check: ${row.x}`);
    lines.push(`Next action: ${row.next}`);
    lines.push("");
  }

  lines.push(
    "Promotion rule: do not describe a pack as `reviewed` unless `src/data/glossary.index.json` and the pack `qaSignals` both carry closed review evidence."
  );
  return `${lines.join("\n")}\n`;
}

function printStatus(index = readJson(INDEX_PATH)) {
  process.stdout.write(formatConsole(rowsFromIndex(index)));
}

function argValue(name) {
  const index = process.argv.indexOf(name);
  if (index === -1 || index === process.argv.length - 1) return "";
  return process.argv[index + 1];
}

if (require.main === module) {
  const markdown = formatMarkdown();
  const outPath = argValue("--out");
  const checkPath = argValue("--check");

  if (outPath) {
    writeFileSync(join(ROOT, outPath), markdown);
  } else if (checkPath) {
    const actual = readFileSync(join(ROOT, checkPath), "utf8");
    if (actual !== markdown) {
      throw new Error(`${checkPath} is out of date. Run npm run glossary:scoreboard.`);
    }
    console.log("glossary status ok");
  } else if (process.argv.includes("--markdown")) {
    process.stdout.write(markdown);
  } else {
    printStatus();
  }
}

module.exports = {
  formatConsole,
  formatMarkdown,
  nextAction,
  printStatus,
  rowsFromIndex,
  summaryFromRows
};
